/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hu.nextent.peas.task.api;

import hu.nextent.peas.model.ErrorMessageModel;
import hu.nextent.peas.model.TaskCreateModel;
import hu.nextent.peas.model.TaskItemPageModel;
import hu.nextent.peas.model.TaskModel;
import hu.nextent.peas.model.TaskQueryParameterModel;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
@Api(value = "task_v1", description = "the task_v1 API")
public interface TaskV1Api {

    Logger log = LoggerFactory.getLogger(TaskV1Api.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }
	

    @ApiOperation(value = "Szerkeszthető task másolása", nickname = "copyTask", notes = "Szerkeszthető task másolása Az következő taskok másolhatóak:   - Saját taskjai   - Vezető taskjai A másolás során az értékelők nem kerülnek másolásra. A task NORMAL típusként jön létre", response = TaskModel.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Másolt task", response = TaskModel.class),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1/copy_v1/{taskId}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<TaskModel> copyTask(@ApiParam(value = "Kiválasztott szerkeszthető task",required=true) @PathVariable("taskId") Long taskId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", TaskModel.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Új szerkeszthető task létrehozása", nickname = "createTask", notes = "Új szerkeszthető task létrehozása", response = TaskModel.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Paraméterezhető task", response = TaskModel.class),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<TaskModel> createTask(@ApiParam(value = "" ,required=true )  @Valid @RequestBody TaskCreateModel body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", TaskModel.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Szerkeszthető task törlése", nickname = "deleteTask", notes = "Szerkeszthető task törlése Törölhető, amelyik:     - a felhasználó saját tulajdonában van      - Aktív     - szerkeszthető státuszú", authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sikeres törlés"),
        @ApiResponse(code = 204, message = "Nincs válasz"),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1/{taskId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteTask(@ApiParam(value = "Kiválasztott task",required=true) @PathVariable("taskId") Long taskId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Adott referenciával rendelkező task lekérdezése", nickname = "getTask", notes = "Adott referenciával rendelkező task lekérdezése Minden olyan task lekérdhető, amely:   * Aktív   * Role esetén:     * ADMIN: Minegyik     * HR: Mindegyik     * USER: Saját     * LEADER: Saját és beosztottak", response = TaskModel.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Taskok lekérdezás", response = TaskModel.class),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1/{taskId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<TaskModel> getTask(@ApiParam(value = "Kiválasztott task",required=true) @PathVariable("taskId") Long taskId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", TaskModel.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Szerkeszthető task módosítása", nickname = "modifyTask", notes = "Szerkeszthető task módosítása Amelyik    - a felhasználó saját tulajdonában van    - Aktív   - szerkeszthető státuszú", response = TaskModel.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Lekérdezett szerkeszthető task", response = TaskModel.class),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1/{taskId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<TaskModel> modifyTask(@ApiParam(value = "" ,required=true )  @Valid @RequestBody TaskModel body,@ApiParam(value = "Kiválasztott task",required=true) @PathVariable("taskId") Long taskId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", TaskModel.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Taskok lekérdezése", nickname = "queryTask", notes = "Taskok lekérdezése Itt csak saját és beosztottak taskjai kérdezhetőek le", response = TaskItemPageModel.class, authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Taskok lekérdezése", response = TaskItemPageModel.class),
        @ApiResponse(code = 204, message = "Nincs válasz"),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<TaskItemPageModel> queryTask(@ApiParam(value = "" ,required=true )  @Valid @RequestBody TaskQueryParameterModel body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", TaskItemPageModel.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Értékelés indítása", nickname = "startEvaluation", notes = "Értékelés indítása Csak olyan taskok szerkeszthetőek, amelyeknél igaz, hogy: - rendelkezik értékelőkkel - típusa: NORMAL/AUTOMATIC - státusza: PARAMETERIZATION", authorizations = {
        @Authorization(value = "bearerAuth")    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sikeres indítás"),
        @ApiResponse(code = 200, message = "Általános hibaüzenet", response = ErrorMessageModel.class) })
    @RequestMapping(value = "/task_v1/start_evaluation/{taskId}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Void> startEvaluation(@ApiParam(value = "Kiválasztott szerkeszthető task",required=true) @PathVariable("taskId") Long taskId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default TaskV1Api interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
