package hu.nextent.peas.jpa.dao;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import hu.nextent.peas.jpa.entity.Role;
import hu.nextent.peas.jpa.entity.User;
import hu.nextent.peas.jpa.entity.UserXRole;

/**
* Generated by Spring Data Generator on 19/09/2019
*/
public interface UserXRoleRepository extends JpaRepository<UserXRole, Long>, JpaSpecificationExecutor<UserXRole> {

	public List<UserXRole> findAllByUser(User user);
	public List<UserXRole> findAllByRole(Role user);
	
}
